#!/bin/sh
# obmc-console-start.sh
#
# Wrapper script that generates obmc-console-multi.conf at runtime with the
# correct remote-host last octet read from /run/openbmc/bmc_position, then
# exec's the console server.  The file contains either 0 or 1.
#
# If /run/openbmc/bmc_position is missing or empty, the script falls back to
# octet 0 and logs a warning.

BMC_POSITION_FILE="/run/openbmc/bmc_position"
CONF_OUT="/run/obmc-console/obmc-console-multi.conf"
CONSOLE_SERVER="/usr/bin/console_server"

# Read last octet from position file
if [ -f "$BMC_POSITION_FILE" ]; then
    LAST_OCTET=$(tr -d '[:space:]' < "$BMC_POSITION_FILE")
else
    echo "WARNING: $BMC_POSITION_FILE not found, defaulting remote-host last octet to 0" >&2
    LAST_OCTET=0
fi

# Validate: must be 0 or 1
case "$LAST_OCTET" in
    0|1) ;;
    *)
        echo "WARNING: unexpected bmc_position value '$LAST_OCTET', defaulting to 0" >&2
        LAST_OCTET=0
        ;;
esac

# The remote peer is always the *other* BMC:
#   this BMC is 0  →  remote is 9.6.28.101
#   this BMC is 1  →  remote is 9.6.28.100
if [ "$LAST_OCTET" -eq 0 ]; then
    REMOTE_LAST_OCTET=101
else
    REMOTE_LAST_OCTET=100
fi

echo "INFO: bmc_position=${LAST_OCTET}, remote-host will be 9.6.28.${REMOTE_LAST_OCTET}" >&2

# Ensure output directory exists
mkdir -p "$(dirname "$CONF_OUT")"

# Generate the config with the resolved IP
cat > "$CONF_OUT" <<EOF
# OBMC Console Server Configuration - Multiple Devices
# Auto-generated by obmc-console-start.sh at boot.
# Do NOT edit by hand — edit obmc-console-start.sh or obmc-console-multi.conf instead.

# Global settings
logsize = 256k
logfile = /var/log/obmc-console.log

# Host boot console - VUART0 (Main console)
[console.host]
lpc-address = 0x3f8
sirq = 4
console-id = host
logsize = 256k
logfile = /var/log/obmc-console0.log
device = /dev/ttyVUART0
device-type = vuart
socket-path = /var/run/obmc-console-host.sock
local-tty-baud = 115200

# Hypervisor debug console - VUART1
[console.hypervisor1]
lpc-address = 0x2f8
sirq = 3
console-id = hypervisor1
logsize = 256k
logfile = /var/log/obmc-console1.log
device = /dev/ttyVUART1
device-type = vuart
socket-path = /var/run/obmc-console-hypervisor1.sock
local-tty-baud = 115200

# Interactive bash shell
[console.bash]
device = /dev/ptmx
device-type = pty
socket-path = /var/run/console-bash.sock
shell-path = /bin/bash
shell-args = -i

# Interactive Python shell
[console.python]
device = /dev/ptmx
device-type = pty
socket-path = /var/run/console-python.sock
shell-path = /usr/bin/python3
shell-args = -i

# IBM i 5250 emulator backend running in console_server.
[console.ibmi_emulator]
device-type = ibmi-emulator
socket-path = /var/run/obmc-console-ibmi.sock
socket-mode = 0660
socket-group = hostconsole

# Remote SSH console — IP resolved from /run/openbmc/bmc_position
[console.remote]
device = /dev/ptmx
device-type = ssh-pty
socket-path = /var/run/obmc-console-remote.sock
socket-mode = 0666
socket-group = hostconsole
remote-host = 9.6.28.${REMOTE_LAST_OCTET}
remote-user = service
remote-password = 0penBmc
remote-port = 22
remote-shell = /bin/bash
connect-timeout = 30
local-tty-baud = 115200
EOF

exec "$CONSOLE_SERVER" "$CONF_OUT" default
